[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true
formatter = { command = "sh", args = ["-c", "ruff check --quiet --select I --fix - | ruff format -"]}

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]
# settings = {
#   lint = {
#     select = ["FBT"]
#   }
# }

# [language.debugger]
# name = "debugpy"
# transport = "stdio"
# command = "python"
# args = ["-m",  "debugpy.adapter"]

# [[language.debugger.templates]]
# name = "source"
# request = "launch"
# completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
# args = { mode = "debug", program = "{0}" }

[[language]]
name = "markdown"
soft-wrap.enable = true
